/*
 * This source file was generated by the Gradle 'init' task
 */
package simanessa;

public class App {
    public String getGreeting() {
        return " hanakdahfoiajkfn Halo Anies Baswedan, selamat datang di dunia Java!";
    }



    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
